version: 2.1

jobs:
  build:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - checkout
      - run: time

  test:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - checkout
      - run: sleep 30

workflows:
  build-workflow:
    when: pipeline.git.branch == "scary-feature"
    jobs:
      - build
      - hold:
          type: approval
      - test
