version: 2.1

jobs:
  build:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - checkout
      - run: time

  test:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - checkout
      - run: sleep 30

  print-tag:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - run: echo "<< pipeline.git.tag >>"

workflows:
  build-workflow:
    when: pipeline.git.branch == "scary-feature"
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires:
            - hold

  tag-workflow:
    jobs:
      - print-tag:
          filters:
            tags:
              only: /^very-important-release.*/
