version: 2.1

jobs:
  build:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - checkout
      - run: time

  test:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - checkout
      - run: sleep 30

  print-tag:
    docker:
      - image: cimg/clojure:1.12.0-openjdk-8.0-node
    steps:
      - run: echo "<< pipeline.git.tag >>"

  random-job:
    type: no-op

  all-good:
    steps:
      - run: echo "all good"

workflows:
  build-workflow:
    when: pipeline.git.branch == "scary-feature"
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - test:
          requires:
            - hold

  tag-workflow:
    jobs:
      - print-tag:
          filters:
            # run for tags starting with very-important-release BUT NOT FOR ANY BRANCHES
            tags:
              only: /^very-important-release.*/
            branches:
              ignore: /.*/

  against-all-odds:
    jobs:
      - random-job
      - all-good:
        requires:
          # doesn't care if it passed or failed
          - random-job:
              - failed
              - canceled
