version: 2.1

parameters:
  run-workflow-docs:
    type: boolean
    default: false
  run-workflow-src:
    type: boolean
    default: false

jobs:
  build-docs:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Docs built"

  build-src:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "src built"

workflows:
  workflow-docs:
    when: << pipeline.parameters.run-workflow-docs >>
    jobs:
      - build-docs

  workflow-src:
    when: << pipeline.parameters.run-workflow-src >>
    jobs:
      - build-src
